# Generated by Django 4.2.9 on 2024-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessagesALL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("hot", models.CharField(max_length=20)),
                ("url", models.URLField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
