# Generated by Django 4.2.9 on 2024-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect_number", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesall",
            name="source",
            field=models.CharField(default="1", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="messagesall",
            name="hot",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="messagesall", name="url", field=models.URLField(max_length=256),
        ),
    ]
