# Generated by Django 4.2.9 on 2024-01-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect_number", "0002_messagesall_source_alter_messagesall_hot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesall",
            name="keyword",
            field=models.CharField(default=" ", max_length=20),
            preserve_default=False,
        ),
    ]
