# Generated by Django 4.2.9 on 2024-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect_number", "0004_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagesall",
            name="hot",
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name="messagesall",
            name="keyword",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="messagesall",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="process",
            name="hot",
            field=models.IntegerField(default=100, null=True),
        ),
    ]
